#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

required_files=(
  VERSION
  METHODOLOGY_VERSION
  README.md
  README_ru.md
  ROADMAP.md
  AI_EVALUATION_GUIDE.md
  AGENTS.md
  ADOPTERS.md
  .vcp/index.json
  .vcp/cards/README.md
  llms-full.txt
  ai.txt
  CITATION.cff
  ANTI_PATTERNS.md
  LICENSE
  DISCLAIMER.md
  CHANGELOG.md
  CLAUDE.md
  AI_INTAKE.md
  AGENTS.md
  .gitattributes
  .github/copilot-instructions.md
  docs/badges.md
  docs/community.md
  docs/community-feedback.md
  docs/target-project-classifier.md
  docs/adoption-packs.md
  docs/route-map.md
  docs/demo.md
  docs/demo-output.md
  docs/release-checklist.md
  docs/community-issues.md
  docs/awesome-vibe-coding-pr.md
  docs/multi-agent-workflows.md
  docs/vibe-metrics.md
  docs/automated-vibe-check.md
  docs/ide-rules-dry-policy.md
  docs/self-dogfooding.md
  docs/release-readiness.md
  docs/adoption-feedback.md
  docs/known-limitations.md
  docs/faq.md
  docs/comparison.md
  docs/anti-patterns.md
  docs/workflows.md
  docs/diagnostics.md
  docs/catalog.md
  docs/event-schema.md
  docs/demo-script.md
  docs/quickstart-walkthrough.md
  docs/adaptive-spec-depth.md
  docs/spec-escape-hatch.md
  docs/question-engine.md
  docs/spec-retrofit.md
  docs/spec-freshness.md
  docs/packs-and-presets.md
  docs/integrations/spec-kit-bridge.md
  docs/progressive-disclosure.md
  docs/vcp-cards.md
  docs/vcp-mappings.md
  docs/cli.md
  docs/install.md
  docs/glossary.md
  docs/scoring.md
  docs/npm-publishing-checklist.md
  docs/public-proof-roadmap.md
  docs/windows.md
  docs/platforms/README.md
  docs/platforms/claude-code.md
  docs/platforms/codex-cli.md
  docs/platforms/cursor.md
  docs/platforms/windsurf.md
  docs/platforms/github-copilot.md
  docs/platforms/gemini-cli.md
  docs/platforms/jetbrains-junie.md
  docs/platforms/aider.md
  docs/platforms/amazon-q-developer.md
  docs/platforms/bolt-new.md
  docs/platforms/cline.md
  docs/platforms/continue.md
  docs/platforms/devin.md
  docs/platforms/google-jules.md
  docs/platforms/lm-studio-local-workflow.md
  docs/platforms/lovable.md
  docs/platforms/ollama-local-coding.md
  docs/platforms/openhands.md
  docs/platforms/qwen-code.md
  docs/platforms/replit-agent.md
  docs/platforms/roo-code.md
  docs/platforms/sourcegraph-cody.md
  docs/platforms/tabnine.md
  docs/platforms/trae.md
  docs/platforms/v0-dev.md
  docs/platforms/vs-code-ai-assistants.md
  docs/platforms/zed-ai.md
  docs/integrations/README.md
  docs/integrations/claude-code.md
  docs/integrations/codex.md
  docs/integrations/cursor.md
  docs/integrations/windsurf.md
  docs/integrations/github-copilot.md
  docs/integrations/jetbrains-junie.md
  docs/ide-plugins.md
  docs/boundary-linting.md
  docs/markdown-style.md
  docs/ecosystem-references.md
  docs/security-tooling-landscape.md
  docs/protocol-index.md
  docs/public-site-readiness.md
  docs/seo-ai-crawler-readiness.md
  docs/geo-ai-visibility.md
  docs/page-templates.md
  docs/site/README.md
  docs/site/navigation.md
  docs/site/github-pages.md
  docs/site/information-architecture.md
  docs/site/publishing-checklist.md
  docs/vibe-check-doctor.md
  docs/vibe-check-init-report.md
  docs/architecture-map.md
  docs/deploy-path.md
  docs/up-to-date-docs-policy.md
  docs/ecosystem.md
  docs/mirrors.md
  docs/mirror-sync.md
  docs/starter-template-intake.md
  docs/update-copied-artifacts.md
  docs/prompt-drift-control.md
  docs/vibe-check-reference.md
  docs/npm-wrapper.md
  docs/python-wrapper.md
  docs/vscode-extension.md
  docs/release-v0.4.2.md
  docs/release-v0.4.3.md
  docs/release-v0.4.4.md
  docs/release-v0.5.0.md
  docs/release-v0.5.1.md
  docs/release-v0.5.2.md
  docs/release-v0.5.6.md
  docs/release-v0.5.7.md
  docs/release-v0.5.8.md
  docs/release-v0.5.9.md
  docs/release-v0.6.0.md
  docs/release-v0.5.5.md
  docs/release-v0.5.4.md
  docs/project-backlog.md
  docs/production-observability.md
  docs/automation-guidance.md
  docs/npm.md
  docs/init.md
  docs/adoption-packs.quickstart.md
  docs/roadmap.md
  docs/measured-impact.md
  .vcp/README.md
  protocols/integrations/README.md
  protocols/public-growth/README.md
  protocols/public-growth/public-growth-playbook.md
  protocols/public-growth/seo-geo-ai-visibility.md
  protocols/public-growth/page-template-system.md
  protocols/public-growth/public-growth-risk-control.md
  protocols/operations/README.md
  protocols/operations/production-error-capture.md
  protocols/operations/daily-error-triage.md
  protocols/spec-driven/README.md
  protocols/spec-driven/adaptive-spec-depth.md
  protocols/spec-driven/product-brief-to-prd.md
  protocols/spec-driven/feature-spec.md
  protocols/spec-driven/question-engine.md
  protocols/spec-driven/spec-escape-hatch.md
  protocols/spec-driven/spec-freshness.md
  protocols/spec-driven/spec-retrofit.md
  protocols/spec-driven/spec-review.md
  protocols/spec-driven/spec-to-tasks.md
  protocols/spec-driven/spec-change-control.md
  .vcp/catalog.json
  .vcp/presets/README.md
  .vcp/presets/agency-client.json
  .vcp/presets/legaltech.json
  .vcp/presets/public-site-defaults.json
  .vcp/presets/saas.json
  .vcp/presets/solo-founder.json
  .vcp/workflows/README.md
  .vcp/diagnostics/README.md
  commands/prod-log-monitor.md
  commands/daily-error-triage.md
  commands/backlog-update.md
  commands/spec-intake.md
  commands/spec-review.md
  commands/spec-to-tasks.md
  protocols/integrations/third-party-api-intake.md
  commands/third-party-api-intake.md
  protocols/review/README.md
  protocols/review/post-task-code-review.md
  commands/loop-code-review.md
  templates/prompts/loop-code-review.md
  templates/reports/code-review-report.md
  examples/review/README.md
  examples/review/loop-code-review.example.md
  examples/review/no-actionable-findings.example.md
  examples/review/rejected-finding.example.md
  docs/release-v0.3.0.md
  docs/pre-commit-hooks.md
  docs/cli-roadmap.md
  docs/release-v0.1.1.md
  scripts/README.md
  scripts/vibe-check.sh
  scripts/check-version-consistency.sh
  scripts/check-ide-rules-consistency.sh
  scripts/check-newlines.py
  scripts/tests/test-vcp-cli.sh
  scripts/tests/test-vcp-cli-windows-parity.py
  scripts/init-project.example.sh
  package.json
  setup.py
  pyproject.toml
  comparison.md
  llms.txt
  .vcp/manifests/vcp.manifest.json
  .vcp/manifests/protocols.manifest.json
  .vcp/manifests/adoption-packs.manifest.json
  .vcp/manifests/commands.manifest.json
  .vcp/manifests/reports.manifest.json
  .vcp/manifests/benchmarks.manifest.json
  schemas/vcp-card.schema.json
  schemas/vcp-preset.schema.json
  schemas/vcp-workflow.schema.json
  schemas/vcp-event.schema.json
  bin/vcp
  bin/vcp.cmd
  bin/vcp.ps1
  bin/vcp-node.js
  bin/vibe-check.js
  vcp_cli/__main__.py
  vcp_cli/cli.py
  vcp_cli/version.py
  vcp_cli/doctor.py
  vcp_cli/check.py
  vcp_cli/route.py
  vcp_cli/adopt.py
  vcp_cli/evaluate.py
  vcp_cli/index_cmd.py
  vcp_cli/cards.py
  vcp_cli/spec_cmd.py
  vcp_cli/workflow_cmd.py
  vcp_cli/diagnose.py
  vcp_cli/score.py
  vcp_cli/manifest.py
  vcp_cli/benchmark.py
  vcp_cli/review.py
  vcp_cli/demo.py
  vcp_cli/utils.py
  vscode-extension/package.json
  vscode-extension/README.md
  vscode-extension/src/extension.ts
  assets/social-preview.svg
  assets/demo/README.md
  templates/ARCHITECTURE_MAP.md
  templates/THIRD_PARTY_REGISTRY.md
  templates/prompts/evaluate-vcp-for-my-repo.md
  templates/prompts/evaluate-vcp-repository.md
  templates/prompts/third-party-api-intake.md
  templates/prompts/prod-log-monitor.md
  templates/prompts/daily-error-triage.md
  templates/prompts/backlog-update.md
  templates/prompts/public-growth-audit.md
  templates/prompts/product-brief-to-prd.md
  templates/prompts/ask-one-question-at-a-time.md
  templates/prompts/review-prd-for-gaps.md
  templates/prompts/spec-question-engine.md
  templates/prompts/spec-retrofit.md
  templates/prompts/spec-to-tasks.md
  templates/reports/vcp-adoption-assessment.md
  templates/reports/vcp-repository-evaluation-report.md
  templates/reports/third-party-api-intake-report.md
  templates/reports/production-error-capture-report.md
  templates/reports/daily-error-triage-report.md
  templates/reports/error-inbox-entry.md
  templates/reports/backlog-update-report.md
  templates/reports/public-growth-audit-report.md
  templates/reports/ai-visibility-monitoring-report.md
  templates/reports/diagnostic-report.md
  templates/reports/vcp-event-entry.md
  templates/reports/spec-depth-decision-report.md
  templates/reports/spec-freshness-report.md
  templates/reports/spec-questions-report.md
  templates/reports/spec-retrofit-report.md
  templates/reports/spec-skip-check-report.md
  templates/reports/spec-to-backlog-report.md
  templates/PROJECT_BACKLOG.md
  templates/specs/PRD.md
  templates/specs/FEATURE_SPEC.md
  templates/specs/OBSERVED_SPEC.md
  templates/specs/SPEC_GAPS.md
  templates/specs/ACCEPTANCE_CRITERIA.md
  templates/specs/TASKS.md
  templates/specs/SPEC_REVIEW.md
  templates/specs/SPEC_CHANGELOG.md
  PROJECT_BACKLOG.md
  templates/protocol-pack-metadata.yml
  templates/reports/security-review-scope.md
  templates/public-site/README.md
  templates/public-site/llms.txt
  templates/public-site/robots.txt
  templates/public-site/schema-org.organization.jsonld
  templates/public-site/schema-org.website.jsonld
  templates/public-site/schema-org.software-source-code.jsonld
  templates/public-site/schema-org.breadcrumb-list.jsonld
  templates/public-site/schema-org.faq-page.jsonld
  templates/public-growth/page-brief.md
  templates/public-growth/service-page-template.md
  templates/public-growth/article-template.md
  templates/public-growth/case-study-template.md
  templates/public-growth/faq-page-template.md
  templates/public-growth/comparison-page-template.md
  templates/public-growth/alternatives-page-template.md
  templates/public-growth/homepage-template.md
  templates/public-growth/public-growth-checklist.md
  templates/public-growth/ai-visibility-queries.md
  templates/public-growth/schema/README.md
  templates/public-growth/schema/organization.jsonld
  templates/public-growth/schema/person.jsonld
  templates/public-growth/schema/service.jsonld
  templates/public-growth/schema/article.jsonld
  templates/public-growth/schema/faqpage.jsonld
  templates/public-growth/schema/breadcrumb-list.jsonld
  templates/public-growth/schema/software-application.jsonld
  templates/public-growth/schema/video-object.jsonld
  examples/architecture-map-example.md
  examples/adoption/dual-production-engine/README.md
  examples/adoption/dual-production-engine/target-profile.md
  examples/adoption/dual-production-engine/recommended-pack.md
  examples/adoption/dual-production-engine/adoption-assessment.example.md
  examples/integrations/README.md
  examples/integrations/public-api-intake.example.md
  examples/integrations/third-party-registry-entry.example.md
  examples/public-growth/README.md
  examples/public-growth/public-growth-audit.example.md
  examples/public-growth/ai-visibility-monitoring.example.md
  examples/public-growth/page-brief.example.md
  examples/public-growth/service-page.example.md
  examples/public-growth/faq-schema.example.md
  examples/backlog/README.md
  examples/backlog/add-idea.example.md
  examples/backlog/move-doing.example.md
  examples/backlog/done-with-review.example.md
  examples/backlog/archive-not-taken.example.md
  examples/backlog/architecture-impact.example.md
  examples/backlog/prod-error-to-backlog.example.md
  examples/operations/README.md
  case-studies/sanitized/vcp-retrofit-public-growth/README.md
  examples/operations/error-inbox-entry.example.md
  examples/operations/daily-error-triage-report.example.md
  examples/operations/project-backlog.example.md
  benchmarks/ai-adoption/README.md
  benchmarks/ai-adoption/expected/README.md
  benchmarks/ai-adoption/scenarios/new-project.json
  benchmarks/ai-adoption/scenarios/existing-mvp.json
  benchmarks/ai-adoption/scenarios/production-saas.json
  benchmarks/ai-adoption/scenarios/regulated-payments-data.json
  benchmarks/ai-adoption/scenarios/shared-engine-production.json
  benchmarks/ai-adoption/scenarios/third-party-api-intake.json
  benchmarks/ai-adoption/scenarios/production-error-capture.json
  benchmarks/ai-adoption/scenarios/project-backlog-update.json
  benchmarks/ai-adoption/scenarios/backlog-add-idea.json
  benchmarks/ai-adoption/scenarios/backlog-move-done-with-review.json
  benchmarks/ai-adoption/scenarios/backlog-archive-not-taken.json
  benchmarks/ai-adoption/scenarios/backlog-architecture-impact.json
  benchmarks/ai-adoption/scenarios/repository-evaluation-full.json
  benchmarks/ai-adoption/scenarios/repository-evaluation-shallow.json
  benchmarks/ai-adoption/scenarios/public-growth-audit.json
  benchmarks/ai-adoption/scenarios/geo-ai-visibility.json
  benchmarks/ai-adoption/scenarios/page-template-selection.json
  benchmarks/ai-adoption/scenarios/glossary-inspection.json
  benchmarks/ai-adoption/scenarios/llms-full-reference.json
  benchmarks/ai-adoption/scenarios/faq-comparison-inspection.json
  benchmarks/ai-adoption/scenarios/anti-patterns-inspection.json
  benchmarks/ai-adoption/scenarios/quickstart-walkthrough-inspection.json
  benchmarks/ai-adoption/scenarios/progressive-disclosure-index.json
  benchmarks/ai-adoption/scenarios/card-based-route-selection.json
  benchmarks/ai-adoption/scenarios/platform-compatibility-inspection.json
  benchmarks/ai-adoption/scenarios/spec-first-product-brief.json
  benchmarks/ai-adoption/scenarios/prd-gap-review.json
  benchmarks/ai-adoption/scenarios/feature-spec-to-tasks.json
  benchmarks/ai-adoption/scenarios/workflow-production-hardening.json
  benchmarks/ai-adoption/scenarios/spec-depth-governed.json
  benchmarks/ai-adoption/scenarios/spec-depth-no-spec.json
  benchmarks/ai-adoption/scenarios/spec-depth-spec-lite.json
  benchmarks/ai-adoption/scenarios/spec-freshness-stale.json
  benchmarks/ai-adoption/scenarios/spec-question-engine.json
  benchmarks/ai-adoption/scenarios/spec-retrofit-existing-code.json
  benchmarks/ai-adoption/scenarios/spec-skip-check-safe.json
  benchmarks/ai-adoption/scenarios/spec-skip-check-unsafe.json
  benchmarks/ai-adoption/scenarios/preset-solo-founder.json
  benchmarks/ai-adoption/scenarios/platform-25-plus-coverage.json
  benchmarks/ai-adoption/scenarios/workflow-public-growth-audit.json
  benchmarks/ai-adoption/scenarios/diagnostics-layer-check.json
  benchmarks/ai-adoption/scenarios/catalog-filter-selection.json
  benchmarks/ai-adoption/scenarios/event-schema-review-finding.json
  benchmarks/ai-adoption/scenarios/maintenance-refactor.json
  benchmarks/ai-adoption/scenarios/ui-ownership.json
  benchmarks/ai-adoption/scenarios/public-site.json
  benchmarks/ai-adoption/scenarios/post-task-review.json
  examples/bad-to-good/README.md
  examples/bad-to-good/maintenance-refactor-before.md
  examples/bad-to-good/maintenance-refactor-after.md
  examples/bad-to-good/ui-ownership-before.md
  examples/bad-to-good/ui-ownership-after.md
  examples/bad-to-good/hardening-before.md
  examples/bad-to-good/hardening-after.md
  case-studies/synthetic-before-after/README.md
  case-studies/sanitized/README.md
  case-studies/sanitized/redaction-checklist.md
  case-studies/sanitized/case-study-template.md
  case-studies/sanitized/measured-impact-template.md
  case-studies/sanitized/synthetic-measured-impact-example.md
  case-studies/sanitized/ai-skim-failure-to-full-hardening/README.md
  case-studies/sanitized/shared-engine-production/README.md
  case-studies/sanitized/post-task-review-found-critical/README.md
  case-studies/redaction-guide.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs_feedback.md
  .github/ISSUE_TEMPLATE/unsafe_guidance.md
  .github/ISSUE_TEMPLATE/integration_request.md
  .github/ISSUE_TEMPLATE/case_study_submission.md
  .github/ISSUE_TEMPLATE/share-your-agents.yml
)

required_dirs=(
  protocols
  protocols/integrations
  prompts
  templates
  templates/prompts
  agents
  examples
  examples/adoption
  examples/integrations
  examples/public-growth
  examples/backlog
  examples/operations
  benchmarks
  benchmarks/ai-adoption
  benchmarks/ai-adoption/scenarios
  checklists
  docs
  docs/integrations
  docs/site
  docs/platforms
  protocols/review
  protocols/public-growth
  protocols/operations
  protocols/spec-driven
  scripts
  assets
  .github/workflows
  examples/todo-app-vibe
  examples/telegram-bot-vibe
  examples/landing-page-vibe
  examples/saas-backend-vibe
  examples/legacy-ai-mess-vibe
  examples/bad-to-good
  examples/review
  case-studies/sanitized
  .vcp
  .vcp/manifests
  .vcp/cards
  .vcp/workflows
  .vcp/diagnostics
  templates/specs
  )

for file in "${required_files[@]}"; do
  [[ -f "$file" ]] || { echo "Missing required file: $file"; exit 1; }
done

for dir in "${required_dirs[@]}"; do
  [[ -d "$dir" ]] || { echo "Missing required directory: $dir"; exit 1; }
done

empty_md=$(find . -type f -name '*.md' -size 0 | sed 's#^./##')
if [[ -n "$empty_md" ]]; then
  echo "Empty markdown files found:"
  echo "$empty_md"
  exit 1
fi

bash scripts/check-version-consistency.sh
bash scripts/check-ide-rules-consistency.sh
python3 scripts/check-newlines.py
python3 -m vcp_cli manifest validate
python3 -m vcp_cli benchmark run

echo "Toolkit structure check passed."
